evaluate: True
ood_detection: True

pretrain:
#    path: model_zoo/AVA_SLOWFAST_R50_ACAR_HR2O.pth.tar
    path: experiments/AVA/20220328_OOD_SLOWFAST_R50_ACAR_HR2O/ckpt_10.pth.tar


result_path: experiments/AVA/eval_SLOWFAST_R50_ACAR_HR2O
manual_seed: 1
print_freq: 20

model:
    freeze_bn: True
    backbone:
        arch: slowfast50
        learnable: True
        kwargs:
            alpha: 4
            beta: 0.125
            fuse_only_conv: False
            fuse_kernel_size: 7
            slow_full_span: True
    neck:
        type: basic
        kwargs:
            bbox_jitter:
                num: 1
                scale: 0.075
            num_classes: 40
            multi_class: False
            ood: True
    head:
        type: acar
        kwargs:
            width: 2304
            roi_spatial: 7
            num_classes: 40
            depth: 2

loss:
    type: ava_criterion
    kwargs:
        pose_softmax: False
        use_edl: True

val:
    root_path: /data/datasets/AVA/frames
    annotation_path: tools/ava_val_v2.2_fair_0.85_40_ood.pkl
    batch_size: 1

    augmentation:
        spatial:
          - type: Scale
            kwargs:
                resize: 256
          - type: ToTensor
            kwargs:
                norm_value: 255.
          - type: Normalize
            kwargs:
                mean: [0.450, 0.450, 0.450]
                std: [0.225, 0.225, 0.225]
        temporal:
            type: TemporalCenterCrop
            kwargs:
                size: 64
                step: 2

    with_label: False

#    eval_mAP:
#        labelmap: tools/ava_acoredl_cls.pbtxt
#        groundtruth: tools/ava_val_v2.2_acoredl_cls.csv
#        exclusions: annotations/ava_val_excluded_timestamps_v2.2.csv

